//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M15_Casino_WS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        public int tableId { get; set; }
        public int cardNum { get; set; }
        public string cardSuit { get; set; }
        public string playerName { get; set; }
        public Nullable<bool> played { get; set; }
        [JsonIgnore]
        public virtual GameCard GameCard { get; set; }
        [JsonIgnore]
        public virtual Player Player { get; set; }
        [JsonIgnore]
        public virtual GameTable GameTable { get; set; }
    }
}
