//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M15_Casino_WS.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyRequest
    {
        public int id { get; set; }
        public string playerName { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<bool> pending { get; set; }
        public Nullable<bool> accepted { get; set; }
        [JsonIgnore]
        public virtual Player Player { get; set; }
    }
}
